// <auto-generated />
using System;
using DataCleaner.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataCleaner.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataCleaner.Api.Entities.CustomerRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("City")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("city");

                    b.Property<int?>("DuplicateGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_group_id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("first_name");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("import_batch_id");

                    b.Property<int>("Issues")
                        .HasColumnType("integer")
                        .HasColumnName("issues");

                    b.Property<string>("LastName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone");

                    b.Property<string>("RawBirthDate")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("raw_birth_date");

                    b.Property<string>("RawCity")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("raw_city");

                    b.Property<string>("RawEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("raw_email");

                    b.Property<string>("RawFullName")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("raw_full_name");

                    b.Property<string>("RawPhone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("raw_phone");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer")
                        .HasColumnName("row_number");

                    b.HasKey("Id")
                        .HasName("pk_customer_records");

                    b.HasIndex("DuplicateGroupId")
                        .HasDatabaseName("ix_customer_records_duplicate_group_id");

                    b.HasIndex("ImportBatchId", "Email")
                        .HasDatabaseName("ix_customer_records_import_batch_id_email");

                    b.HasIndex("ImportBatchId", "Phone")
                        .HasDatabaseName("ix_customer_records_import_batch_id_phone");

                    b.ToTable("customer_records", (string)null);
                });

            modelBuilder.Entity("DataCleaner.Api.Entities.DuplicateGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("integer")
                        .HasColumnName("import_batch_id");

                    b.Property<string>("MatchReason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("match_reason");

                    b.HasKey("Id")
                        .HasName("pk_duplicate_groups");

                    b.HasIndex("ImportBatchId")
                        .HasDatabaseName("ix_duplicate_groups_import_batch_id");

                    b.ToTable("duplicate_groups", (string)null);
                });

            modelBuilder.Entity("DataCleaner.Api.Entities.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("file_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.HasKey("Id")
                        .HasName("pk_import_batches");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("DataCleaner.Api.Entities.CustomerRecord", b =>
                {
                    b.HasOne("DataCleaner.Api.Entities.DuplicateGroup", "DuplicateGroup")
                        .WithMany("Records")
                        .HasForeignKey("DuplicateGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_customer_records_duplicate_groups_duplicate_group_id");

                    b.HasOne("DataCleaner.Api.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Records")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_records_import_batches_import_batch_id");

                    b.Navigation("DuplicateGroup");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("DataCleaner.Api.Entities.DuplicateGroup", b =>
                {
                    b.HasOne("DataCleaner.Api.Entities.ImportBatch", "ImportBatch")
                        .WithMany("DuplicateGroups")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_duplicate_groups_import_batches_import_batch_id");

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("DataCleaner.Api.Entities.DuplicateGroup", b =>
                {
                    b.Navigation("Records");
                });

            modelBuilder.Entity("DataCleaner.Api.Entities.ImportBatch", b =>
                {
                    b.Navigation("DuplicateGroups");

                    b.Navigation("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
